version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: type-orm
      POSTGRES_PASSWORD: type-orm
      POSTGRES_DB: type-orm
    volumes:
      - type-orm-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=type-orm
      - DB_PASSWORD=type-orm
      - DB_NAME=type-orm
    depends_on:
      - db
    command: >
      sh -c "
        npm install &&
        npm run seed &&
        npm run dev
      "

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: npm start

volumes:
  type-orm-data:
