name: 🌐 Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: (Optional) Run frontend tests or lint
        working-directory: frontend
        run: |
          # npm test or eslint . 
          echo "No tests configured yet"

      - name: Trigger Render frontend deploy
        env:
          HOOK: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$HOOK"
